"""
Per-user configuration stored as TOML.

Different from the reference: the original hardcodes paths with getpass interactions.
This uses a declarative TOML config that the CLI reads, making headless operation trivial.
"""

from __future__ import annotations

from pathlib import Path

# We use stdlib tomllib (3.11+) for reading and manual TOML writing.
# No external TOML dependency — keeps the install surface minimal.

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore[no-redef]

import os

DEFAULT_CONFIG_NAME = "technocore.toml"


def _default_config_path() -> Path:
    # XDG-ish: prefer local dir, fall back to home
    local = Path("technocore.toml")
    if local.exists():
        return local
    return Path(os.environ.get("TECHNOCORE_CONFIG", str(Path.home() / ".config" / "technocore.toml")))


def _default_identity_path(config_dir: Path) -> str:
    return str(config_dir.parent / "identity.pem")


class Config:
    """Read-only view of the user's technocore.toml."""

    __slots__ = ("_data", "_path")

    def __init__(self, path: str | Path | None = None) -> None:
        if path is None:
            path = _default_config_path()
        self._path = Path(path)
        if self._path.exists():
            self._data = tomllib.loads(self._path.read_text(encoding="utf-8"))
        else:
            self._data = {}

    @property
    def identity_path(self) -> Path:
        p = self._data.get("identity", {}).get("path")
        if p:
            return Path(p).expanduser().resolve()
        return Path("identity.pem").resolve()

    @property
    def did(self) -> str | None:
        return self._data.get("identity", {}).get("did")

    @property
    def default_room(self) -> str:
        return self._data.get("defaults", {}).get("room", "lobby")

    @property
    def api_base(self) -> str:
        return self._data.get("api", {}).get("base_url", "https://technocore.chat")

    def save_identity(self, identity_path: str, did: str) -> Path:
        """Write a minimal config pointing to the identity file."""
        # TOML always uses forward slashes — convert to avoid escape-sequence issues on Windows
        path = identity_path.replace("\\", "/")
        content = (
            f"# Technocore identity configuration\n"
            f"# Generated by technocore-kit\n"
            f"\n"
            f"[identity]\n"
            f'path = "{path}"\n'
            f'did = "{did}"\n'
            f"\n"
            f"[defaults]\n"
            f'room = "lobby"\n'
            f"\n"
            f"[api]\n"
            f'base_url = "https://technocore.chat"\n'
        )
        self._path.write_text(content, encoding="utf-8")
        return self._path